spring:
  application:
    name: CurrencyService
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=100, expireAfterWrite=1h

management:
  endpoints:
    web:
      exposure:
        include: circuitbreakers

app:
  client:
    url: https://www.cbr.ru/scri—Ñpts/XML_daily.asp

resilience4j:
  circuitbreaker:
    instances:
      currencySystem:
        slidingWindowSize: 5
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 5
        waitDurationInOpenState: 10s
        minimumNumberOfCalls: 3
